# Generated by Django 2.2 on 2020-05-26 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userOrAlgorithm', models.BooleanField()),
                ('algorithmUsed', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fileName', models.CharField(blank=True, max_length=512, null=True)),
                ('fileType', models.CharField(blank=True, max_length=256, null=True)),
                ('chksum', models.CharField(default='', max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadedDate', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('analysisProtocol', models.CharField(blank=True, max_length=255, null=True)),
                ('analysisSubmittedDate', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('analysisCompletedDate', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('submittedOn', models.DateTimeField(blank=True, null=True)),
                ('completedTime', models.DateTimeField(blank=True, null=True)),
                ('jobStatusCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.JobStatusCode')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.Process')),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uploadeFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.UploadFolder')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.Process')),
            ],
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antsCorticalThickness', models.CharField(blank=True, max_length=512, null=True)),
                ('antsIntroduction', models.CharField(blank=True, max_length=512, null=True)),
                ('jointLabelFusion', models.CharField(blank=True, max_length=512, null=True)),
                ('warpImageMultiTransform', models.CharField(blank=True, max_length=512, null=True)),
                ('uploadFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.UploadFolder')),
            ],
        ),
        migrations.CreateModel(
            name='ImijUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(blank=True, max_length=512, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=12, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=512)),
                ('commentDate', models.DateTimeField()),
                ('imageClass', models.IntegerField()),
                ('xPosition', models.IntegerField()),
                ('yPosition', models.IntegerField()),
                ('zPosition', models.IntegerField()),
                ('commentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.CommentType')),
                ('uploadFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.UploadFolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
