# Generated by Django 2.2 on 2020-06-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfolder',
            name='analysisCompletedDate',
        ),
        migrations.RemoveField(
            model_name='uploadfolder',
            name='analysisProtocol',
        ),
        migrations.RemoveField(
            model_name='uploadfolder',
            name='analysisSubmittedDate',
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('channelNum', models.IntegerField()),
                ('samplingFrequency', models.IntegerField()),
                ('upperFrequency', models.IntegerField()),
                ('lowerFrequency', models.IntegerField()),
                ('timeBandWidth', models.IntegerField()),
                ('timeWindow', models.IntegerField()),
                ('stepSize', models.IntegerField()),
                ('numTapers', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('submittedOn', models.DateTimeField()),
                ('completedOn', models.DateTimeField(blank=True, null=True)),
                ('uploadFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.UploadFolder')),
            ],
        ),
    ]
