# Generated by Django 2.2 on 2020-06-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0003_auto_20200630_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisdetailchannel',
            old_name='uploadFolder',
            new_name='analysisDetail',
        ),
    ]
