# Generated by Django 2.2 on 2020-07-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0004_auto_20200630_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdetail',
            name='lowerTimeLimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='upperTimeLimit',
            field=models.IntegerField(null=True),
        ),
    ]
