# Generated by Django 2.2 on 2020-07-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0005_auto_20200708_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdetail',
            name='channel1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='channel2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='computeCrossCorrelationFlag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='computePACFlag',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='computePLVFlag',
            field=models.NullBooleanField(),
        ),
    ]
