# Generated by Django 2.2 on 2020-09-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0007_pacparams_plvparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('uploadFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.UploadFolder')),
            ],
        ),
    ]
