# Generated by Django 2.2 on 2020-10-07 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0009_epoch_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='uploadfolder',
            name='referenceChannel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='uploadfolder',
            name='useMontage',
            field=models.NullBooleanField(),
        ),
        migrations.CreateModel(
            name='MontageChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel1', models.CharField(max_length=256)),
                ('channel2', models.CharField(max_length=256)),
                ('montage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.Montage')),
            ],
        ),
        migrations.AddField(
            model_name='uploadfolder',
            name='montage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eegPortalApp.Montage'),
        ),
    ]
