# Generated by Django 2.2 on 2020-10-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eegPortalApp', '0010_auto_20201007_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='montagechannel',
            name='resultChannel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
